### ISSUE TITLE
Template variables could not be initialized: e.metricfindquery

### ISSUE THREAD

**Issue by wopashugeixianshi** [taosdata/grafanaplugin#11]
hello,

grafana version:6.7.3/7.2.0
Tdengine verison:2.0.8.2

What should I do?

**Comment by maoyaowu** [comment]
Maybe this “Template variables in Grafana” is not supported now。

**Comment by wopashugeixianshi** [comment]
> Maybe this “Template variables in Grafana” is not supported now。

![image](https://user-images.githubusercontent.com/34019284/102049420-ca0fbc00-3e1b-11eb-970d-1d2aef48c9c9.png)
I see that template variables are indeed used in the grafana demo provided by tdengine. Why is it that tdengine database is not used?

**Comment by Jerry217** [comment]
这个问题解决了么？

**Comment by zitsen** [comment]
Already suuported
