### ISSUE TITLE
"Could not find executor for data source type: tdengine-datasource" only for alert

### ISSUE THREAD

**Issue by chen8238065** [taosdata/grafanaplugin#114]
My TDengine graph works fine, but alert rule can not run. I got this detail error message "[tsdb.HandleRequest() error Could not find executor for data source type: tdengine-datasource]()". 

version info：
system                 14.04.1-Ubuntu,
grafana                 v7.3.5, 
grafanaplugin       3.1.3

**Comment by zitsen** [comment]
Could not find executor means backend plugin (with which the alert will work) not installed in your plugin.

Did you install the plugin with the release package https://github.com/taosdata/grafanaplugin/releases/download/v3.1.4/tdengine-datasource-3.1.4.zip or with the github source code tar file? GitHub source code tar file will not work with alert.

Suggest you install the plugin following the latest instruction.

**Comment by chen8238065** [comment]
Yes ,i has installed the latest plugin.

**Comment by chen8238065** [comment]
> work@ajkoffice:/var/lib/grafana/plugins/tdengine-datasource$ ./tdengine-datasource_linux_amd64
open /var/log/grafana/tdengine_backend.log: no such file or directory
panic: open /var/log/grafana/tdengine_backend.log: no such file or directory

Thanks,I has fixed.  Because of   /var/log/grafana directory not exists and wrong user role.
