### ISSUE TITLE
Using the time series to rows mode of table transform, it is found that some data is missing

### ISSUE THREAD

**Issue by wopashugeixianshi** [taosdata/grafanaplugin#12]
Hello, in the process of using Table pannel, I found that the time series to columns mode of table transform was selected, and a part of data was lost, but there was no problem switching to time series to rows. Since I need to display multiple columns of data, I use the time series to columns mode.

The version of grafana I used was 6.7.3
The version of tdengine  I used was 2.0.8.2

**Comment by sangshuduo** [comment]
Please use the latest release of the Grafana plugin. We already support multiple columns.
