### ISSUE TITLE
如何实现类似 Prometheus 展示组件中的 legend 配置。

### ISSUE THREAD

**Issue by ygsa** [taosdata/grafanaplugin#147]
- `TDengine`查询出数据如下
![image](https://user-images.githubusercontent.com/34697347/178407405-97445853-c4b4-4679-837e-c1d5e24e5c82.png)
- 在 `Prometheus` 数据源配置展示图可在 `legend` 中配置 `{{city}}` 从而使展示中每行数据名称为城市名，对应值为查询出的 cnt。类似数据展示如下
![image](https://user-images.githubusercontent.com/34697347/178407895-76afda4c-2ebd-4469-9576-d50834c3e168.png)
- `TDengine` 展示如下，如何让左侧的显示为城市名称？
![image](https://user-images.githubusercontent.com/34697347/178407204-80d95a52-54a4-4a1e-94f3-d7fd0fe7a479.png)

查看了文档中内容，暂未发现可以实现此操作方式。
望解答，感谢~

**Comment by sunpe** [comment]
使用 group by 或 partition by 语法，并且在页面上配置 group by 字段。
<img width="978" alt="image" src="https://user-images.githubusercontent.com/8380506/206619054-34a4cce9-1dd3-4f8a-a711-d6c055a11f16.png">
