### ISSUE TITLE
能不能支持grafana的Variables，页面顶部下拉列表的展示，目前使用插件还是报错 

### ISSUE THREAD

**Issue by Jerry217** [taosdata/grafanaplugin#15]

**Comment by Jerry217** [comment]
![QQ截图20210115192456](https://user-images.githubusercontent.com/41631882/104721310-6d7c2580-5768-11eb-8366-1b6b578f6244.png)
无法在模板也设置查询结果作为菜单的下拉列表，报错如下：
Templating
Template variables could not be initialized: e.metricFindQuery is not a function

**Comment by zitsen** [comment]
Already supported now.
