### ISSUE TITLE
TDengine Data source is not working, reason: Bad Gateway

### ISSUE THREAD

**Issue by jdmedeiros** [taosdata/grafanaplugin#155]
Can not manage to get the data source to work with Grafana v9.2.0; using root and taos data and confirmed that it is working from the command line  `taos -uroot -ptaosdata` and the hostname is in the DNS and working properly. This is just an experiment in one machine.

<img width="628" alt="image" src="https://user-images.githubusercontent.com/3796667/197079136-6c242909-5143-4895-88e1-f99c244e8661.png">

<img width="628" alt="image" src="https://user-images.githubusercontent.com/3796667/197079315-7ab3c013-61fe-42bf-8b95-5dce558858c2.png">

<img width="808" alt="image" src="https://user-images.githubusercontent.com/3796667/197079454-1c19d65a-2ad1-476d-a96c-d579a2469498.png">

<img width="902" alt="image" src="https://user-images.githubusercontent.com/3796667/197079601-c50232b8-fe00-4ed5-92f4-bc44195044d2.png">

**Comment by zitsen** [comment]
Grafana connection will use TDengine RESTful API (served by **taosAdapter** with default port 6041).

Change the port 6030 to 6041 in the dashboard, and test it again.

If still failed, then test your RESTful API connection by following steps in your Grafana server:
1. `ping aaa.bbb.com`
2. `curl -u root:taosdata -d 'show databases' http://aaa.bbb.com:6041`

**Comment by jdmedeiros** [comment]
It worked; I had not seen any reference to the _taosadapter_ and had not started it. Wouldn't be a bad idea to reference it in the datasource documentation. Thanks you!

**Comment by sangshuduo** [comment]
> It worked; I had not seen any reference to the _taosadapter_ and had not started it. Wouldn't be a bad idea to reference it in the datasource documentation. Thanks you!

Thanks for your suggestion. Submitted a PR https://github.com/taosdata/grafanaplugin/pull/156 for it.
