### ISSUE TITLE
请问Grafana和TDengine的版本适配在哪里看？

### ISSUE THREAD

**Issue by kqkdChen** [taosdata/grafanaplugin#197]
**Grafana Version: 7.1.5**
**TDengine Version: 3.0.3.0**
**TDengine Datasource 3.3.1**

如下图，所有的图表都是空的
![image](https://user-images.githubusercontent.com/41674301/227458708-5540a0eb-8fdd-40db-b47b-1d457bd4a34f.png)

使用的如下json 
https://grafana.com/grafana/dashboards/15146-multiple-tdengines-monitoring/

**请问TDengine Datasource Plugin 的版本是否正确？到底是什么原因导致的**

**Comment by kqkdChen** [comment]
![image](https://user-images.githubusercontent.com/41674301/227459669-c7616f13-75c6-4154-b308-50845bf86a77.png)
手动创建图表也会报错

**Comment by sunpe** [comment]
适配 7.5 以上版本
