### ISSUE TITLE
grafana-7.1.1  Unexpected token

### ISSUE THREAD

**Issue by lsxredrain** [taosdata/grafanaplugin#33]
Unexpected token '<' Evaluating http://prod.iotn2n.com:3000/public/app/plugins/datasource/tdengine/module Loading app/plugins/datasource/tdengine/module
Data Source Error

**Comment by afwerar** [comment]
My tdengine plugin works well in grafana:7.1.1. I want to reproduce this problem. Can you provide more information, such as the version of the plug-in used, the plug-in directory, startup commands, error screenshots, detailed information, etc.
![image](https://user-images.githubusercontent.com/20500927/131471074-bba8e250-3cfc-42bb-83a5-3f62e9f85d9c.png)

**Comment by sangshuduo** [comment]
no more update, so close it.
