### ISSUE TITLE
there is no ' /usr/local/taos/connector/grafana' directory.

### ISSUE THREAD

**Issue by assmdx** [taosdata/grafanaplugin#5]
https://www.taosdata.com/blog/2019/07/10/192.html

![image](https://user-images.githubusercontent.com/19722693/92315871-a10eac80-f01e-11ea-9d95-5a88c5accb33.png)

**Comment by axiao43** [comment]
下载 2.0.1.1

**Comment by sangshuduo** [comment]
no more update, so close it.
