### ISSUE TITLE
Can we support alerting in Grafana

### ISSUE THREAD

**Issue by axiao43** [taosdata/grafanaplugin#6]
Error: tsdb.HandleRequest() error Could not find executor for data source type: taosdata-tdengine-datasource
Can we support alerting with tdengine？

**Comment by maoyaowu** [comment]
support alerting in grafana is very imortant！

**Comment by yaobo-lab** [comment]
> Error: tsdb.HandleRequest() error Could not find executor for data source type: taosdata-tdengine-datasource Can we support alerting with tdengine？

This feature is strongly requested

**Comment by afwerar** [comment]
Alerting will be supported in the next version, please wait for a while.

**Comment by zitsen** [comment]
Alerting feature is landed in v3.1.0 and above. Try it following the README.
