### ISSUE TITLE
grafana:8.1.5，高版本grafana中变量无法进行时间范围筛选

### ISSUE THREAD

**Issue by 784134748** [taosdata/grafanaplugin#70]
![image](https://user-images.githubusercontent.com/16873072/141674243-1916d22c-a124-42f3-9789-f7cf36bb31a2.png)

之前提过的issue，不知道是不是提错地方了
https://github.com/taosdata/TDengine/issues/8072

**Comment by afwerar** [comment]
添加变量后是可以查出数据的，你看一下请求的sql语句具体是什么
![image](https://user-images.githubusercontent.com/20500927/142974051-7cc9a4d9-e302-407d-b246-d79c6d423577.png)
![image](https://user-images.githubusercontent.com/20500927/142974084-58b64621-2ca0-444f-a323-1a180e725a83.png)

**Comment by 784134748** [comment]
![截屏2021-11-28 上午11 16 00](https://user-images.githubusercontent.com/16873072/143727483-f6c219ec-e5f7-4241-96c7-64e69047d540.png)

**Comment by 784134748** [comment]
![截屏2021-11-28 上午11 20 42](https://user-images.githubusercontent.com/16873072/143727578-b754955a-71b5-423a-9c1c-b9fd645113b8.png)

**Comment by 784134748** [comment]
![截屏2021-11-28 上午11 22 55](https://user-images.githubusercontent.com/16873072/143727597-19592211-f7a9-4435-809c-ae82984b1957.png)

**Comment by afwerar** [comment]
你用的是不是新版本的插件吗
![GIF 2021-11-28 12-01-55](https://user-images.githubusercontent.com/20500927/143729094-efbab33e-e5a3-4f8a-8fda-018e0b88254c.gif)

**Comment by 784134748** [comment]
插件是从这个2.2.1.3的包里面拿出来的
COPY --from=tdengine/tdengine:2.2.1.3 /root/TDengine-server-*/connector/grafanaplugin /var/lib/grafana/plugins/tdengine

**Comment by afwerar** [comment]
好吧，你直接装最新版本，新的插件不再依赖TDengine版本
grafana-cli --pluginUrl https://github.com/taosdata/grafanaplugin/releases/download/v3.1.3/tdengine-datasource-3.1.3.zip plugins install tdengine-datasource
