### ISSUE TITLE
Not able to install grafana datasource plugin

### ISSUE THREAD

**Issue by vibhubithar** [taosdata/grafanaplugin#73]
Following instruction on the github, i am able to download the plugin but not able to unzip it to the grafana plugin directory

tdengine-datasource-3.1.1.zip   100%[====================================================>]  27.90M  35.4MB/s    in 0.8s    

2021-11-16 17:28:02 (35.4 MB/s) - ‘tdengine-datasource-3.1.1.zip’ saved [29256274/29256274]

(base) vibhu@vibhu-Opti-1-UB20:~$     sudo unzip tdengine-datasource-$GF_VERSION.zip /var/lib/grafana/plugins/
**Archive:  tdengine-datasource-3.1.1.zip
caution: filename not matched:  /var/lib/grafana/plugins/**

Also tried to manually copy the zip file over to plugins directory and change the options in /etc/grafana/grafana.ini

enable_alpha = true
allow_loading_unsigned_plugins = taosdata-tdengine-datasource

Now the Grafana server is not starting

     Loaded: loaded (/lib/systemd/system/grafana-server.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Tue 2021-11-16 18:04:55 PST; 3min 17s ago
       Docs: http://docs.grafana.org
    Process: 2202 ExecStart=/usr/sbin/grafana-server --config=${CONF_FILE} --pidfile=${PID_FILE_DIR}/grafana-server.pid --packaging=deb cfg:default.paths.logs=${LOG_DIR} cfg:default.paths.data=${DATA_D} cfg:default.paths.plugins=${PLUGINS_DIR} cfg:default.paths.provisioning=${PROVISIONING_CFG_DIR} 
   Main PID: 2202 (code=exited, status=1/FAILURE)cfg:default.paths.plugins=${PLUGINS_DIR} cfg:default.paths.provisioning=${PROVISIONING_CFG_DIR} (code=exited, status=1/FAILURE)

Nov 16 18:04:55 vibhu-Opti-1-UB20 systemd[1]: grafana-server.service: Scheduled restart job, restart counter is at 5.
Nov 16 18:04:55 vibhu-Opti-1-UB20 systemd[1]: Stopped Grafana instance.
Nov 16 18:04:55 vibhu-Opti-1-UB20 systemd[1]: grafana-server.service: Start request repeated too quickly.
Nov 16 18:04:55 vibhu-Opti-1-UB20 systemd[1]: grafana-server.service: Failed with result 'exit-code'.
Nov 16 18:04:55 vibhu-Opti-1-UB20 systemd[1]: Failed to start Grafana instance.

**Comment by zitsen** [comment]
> Following instruction on the github, i am able to download the plugin but not able to unzip it to the grafana plugin directory
> 
> tdengine-datasource-3.1.1.zip 100%[====================================================>] 27.90M 35.4MB/s in 0.8s
> 
> 2021-11-16 17:28:02 (35.4 MB/s) - ‘tdengine-datasource-3.1.1.zip’ saved [29256274/29256274]
> 
> (base) vibhu@vibhu-Opti-1-UB20:~$ sudo unzip tdengine-datasource-$GF_VERSION.zip /var/lib/grafana/plugins/ **Archive: tdengine-datasource-3.1.1.zip caution: filename not matched: /var/lib/grafana/plugins/**
> 
> Also tried to manually copy the zip file over to plugins directory and change the options in /etc/grafana/grafana.ini
> 
> enable_alpha = true allow_loading_unsigned_plugins = taosdata-tdengine-datasource
> 
> Now the Grafana server is not starting
> 
> ```
>  Loaded: loaded (/lib/systemd/system/grafana-server.service; enabled; vendor preset: enabled)
>  Active: failed (Result: exit-code) since Tue 2021-11-16 18:04:55 PST; 3min 17s ago
>    Docs: http://docs.grafana.org
> Process: 2202 ExecStart=/usr/sbin/grafana-server --config=${CONF_FILE} --pidfile=${PID_FILE_DIR}/grafana-server.pid --packaging=deb cfg:default.paths.logs=${LOG_DIR} cfg:default.paths.data=${DATA_D} cfg:default.paths.plugins=${PLUGINS_DIR} cfg:default.paths.provisioning=${PROVISIONING_CFG_DIR} 
> ```
> 
> Main PID: 2202 (code=exited, status=1/FAILURE)cfg:default.paths.plugins=${PLUGINS_DIR} cfg:default.paths.provisioning=${PROVISIONING_CFG_DIR} (code=exited, status=1/FAILURE)
> 
> Nov 16 18:04:55 vibhu-Opti-1-UB20 systemd[1]: grafana-server.service: Scheduled restart job, restart counter is at 5. Nov 16 18:04:55 vibhu-Opti-1-UB20 systemd[1]: Stopped Grafana instance. Nov 16 18:04:55 vibhu-Opti-1-UB20 systemd[1]: grafana-server.service: Start request repeated too quickly. Nov 16 18:04:55 vibhu-Opti-1-UB20 systemd[1]: grafana-server.service: Failed with result 'exit-code'. Nov 16 18:04:55 vibhu-Opti-1-UB20 systemd[1]: Failed to start Grafana instance.

`unzip` need  `-d` before install directory
```sh
sudo unzip tdengine-datasource-$GF_VERSION.zip -d /var/lib/grafana/plugins/
```

And the plugin id is `tdengine-datasource`.

```ini
allow_loading_unsigned_plugins = tdengine-datasource
```

**Comment by afwerar** [comment]
You can also manually run the /usr/sbin/grafana-server command to start the program and look at the log.

**Comment by vibhubithar** [comment]
sudo unzip -d tdengine-datasource-$GF_VERSION.zip /var/lib/grafana/plugins/
[sudo] password for vibhu: 
unzip:  cannot find or open /var/lib/grafana/plugins/, /var/lib/grafana/plugins/.zip or /var/lib/grafana/plugins/.ZIP.

**Comment by vibhubithar** [comment]
Grafana not starting was my mistake extra ';'

as for grafana recognizing the tdengine plugin still no luck

screenshot of grafana ini 
![grafana ini](https://user-images.githubusercontent.com/10491706/142268198-afd96adf-b277-4ba4-a912-621b09bc6f6f.png)

screenshot of adding datasource
![TDengine grafana](https://user-images.githubusercontent.com/10491706/142268213-c90da874-e243-4e43-b30b-43fbdd4bdfc9.png)

**Comment by vibhubithar** [comment]
(base) vibhu@vibhu-Opti-1-UB20:~$  /usr/sbin/grafana-server
Grafana-server Init Failed: Could not find config defaults, make sure homepath command line parameter is set or working directory is homepath
(base) vibhu@vibhu-Opti-1-UB20:~$

**Comment by vibhubithar** [comment]
Please fix the documentation at https://www.taosdata.com/en/documentation/connections#grafana
for unzip need -d before install directory

sudo unzip tdengine-datasource-$GF_VERSION.zip -d /var/lib/grafana/plugins/

**Comment by vibhubithar** [comment]
also i am using ubuntu 20.04 and grafana v8.2.4

**Comment by afwerar** [comment]
First you can install the plugin with the following command.
grafana-cli --pluginUrl https://github.com/taosdata/grafanaplugin/releases/download/v3.1.1/tdengine-datasource-3.1.1.zip plugins install tdengine-datasource
In addition, you have to delete ";" to ensure that your configuration takes effect, and then restart grafana.
![image](https://user-images.githubusercontent.com/20500927/142965226-7b0768d9-1326-4b06-8875-a62d0c3ea98d.png)

**Comment by vibhubithar** [comment]
Thanks instructions provided worked well. Please update the instruction online with these.
