### ISSUE TITLE
Grafana pulling only first 10k records

### ISSUE THREAD

**Issue by vibhubithar** [taosdata/grafanaplugin#80]
Ubuntu 20.04
Grafana 8.2.4
Taosdb client version 2.2.1.3 

Here are my data points aggregated over various days when data was collected
Here is the number of data points for a sensor on a specific date
![taosdata-count of gyroscope points by date stamo](https://user-images.githubusercontent.com/10491706/143267395-fbd37d45-6a8e-45c3-a888-cffbb92f8aec.png)

So in grafana i expect i get a line of data on all these dates, when it executes "select ts,gryx_angle from gpsLogger.upboardberry1 WHERE ts > '2021-08-16T07:00:00.000Z' and ts < '2021-11-24T07:59:59.000Z';"

What I am observing is that only the data for 8/16/2021 is returned, even when I set grafana to return a large number of points.
![taosdbgrafana-notall data](https://user-images.githubusercontent.com/10491706/143267731-154f606a-51ec-4a92-aeb6-b123b853b028.png)

![wholedashboard-taosdb-grafana](https://user-images.githubusercontent.com/10491706/143267797-131727e4-59f1-4cad-ba37-5683fb497090.png)

I think there is certainly an issue as same thing happens with single day, it's just returning first 10K rows 
![taosdb-grafana-datapoints](https://user-images.githubusercontent.com/10491706/143267990-e9923e9a-da3a-4a3c-a626-ee90f08b7895.png)

looks like only first 10k rows are returned
![taosdb-grafana-firstfewhoursofdata](https://user-images.githubusercontent.com/10491706/143268005-67d034c8-87b2-483a-ae8f-6df8d6d77168.png)

**Comment by zitsen** [comment]
Legacy restful API has a result rows limitation by default 10240, you can increase it in `/etc/taos/taos.cfg` as
```conf
# max 10000000
restfulRowLimit 1024000
```

BTW, TDengine 2.3 (now in beta) support a new restful service named taosadapter, it has no row limits.

**Comment by sangshuduo** [comment]
> Thanks i updated the config to MAX but grafana is crashing when pulling the data.
> 
> When will the 2.3 be out of Beta?

I believe 2.4 will be released in December.

**Comment by vibhubithar** [comment]
ok will wait for that
