### ISSUE TITLE
多个变量级联筛选，希望变量查询不到数据时可以设置默认值

### ISSUE THREAD

**Issue by 784134748** [taosdata/grafanaplugin#89]
![截屏2021-12-07 上午12 21 57](https://user-images.githubusercontent.com/16873072/144883036-8858816a-da23-4c59-8fed-deff5b5831d8.png)
第一个变量cha查询不到值时，第二个变量查询就会报错，然后dashboard就会卡死，所以希望查不到值是可以设置默认值

**Comment by 784134748** [comment]
![截屏2021-12-07 上午12 25 52](https://user-images.githubusercontent.com/16873072/144883575-776e54ab-2798-4c58-b505-5df35c97f626.png)
情况就是这么个情况，卡死！

**Comment by sangshuduo** [comment]
@784134748 问题解决了吗？

**Comment by 784134748** [comment]
> @784134748 问题解决了吗？
解决了一半吧
![image](https://user-images.githubusercontent.com/16873072/147448924-763944e2-23bf-45b3-b10b-f8b35f6fe18c.png)
通过给all赋值了一个默认值可以解决报错的问题，但事实上我是希望这个选择all的时候，“and host = ”这个条件移除，直接将超级表中所有设备数据都查询出来。

例如：
选择：host = "jmeter-0.jmeter-hs" 时
查询语句：select ts, sum(succeed) from summary_report where exec_id = "123456789" and host = "jmeter-0.jmeter-hs"

选择：host = "jmeter-1.jmeter-hs" 时
查询语句：select ts, sum(succeed) from summary_report where exec_id = "123456789" and host = "jmeter-1.jmeter-hs"

选择：host 为 all 时
查询语句：select ts, sum(succeed) from summary_report where exec_id = "123456789"
