### ISSUE TITLE
报错：_this.arithmeticQueries(...).flat is not a function

### ISSUE THREAD

**Issue by pyx-py** [taosdata/grafanaplugin#95]
new dashboard/Edit Panel的界面报错，sql语句执行是ok的，但是不显示图

**Comment by afwerar** [comment]
详细点的报错截图有吗

**Comment by pyx-py** [comment]
![IMG_20211224_171012](https://user-images.githubusercontent.com/51142411/147340205-cf63fc2c-c4ce-4ed4-8ddd-94679eb75c56.jpg)
![IMG_20211224_170947](https://user-images.githubusercontent.com/51142411/147340215-a48b17a7-f3b5-43e7-b0df-cd41d9d7cce6.jpg)
![IMG_20211224_170932](https://user-images.githubusercontent.com/51142411/147340222-3f592238-23d0-4e5f-b1eb-2c04cb9aad21.jpg)
内网截不了图，只能拍了

**Comment by afwerar** [comment]
你加一下我的微信吧，就是afwerar

**Comment by pyx-py** [comment]
chrome的包有问题，已解决，感谢老哥@afwerar
